# Generated by Django 6.0.5 on 2026-05-08 06:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('date', models.DateTimeField(verbose_name='Дата проведения')),
                ('location', models.CharField(max_length=300, verbose_name='Место проведения')),
                ('prize_fund', models.CharField(blank=True, max_length=100, null=True, verbose_name='Призовой фонд')),
                ('cases_visible_date', models.DateTimeField(verbose_name='Дата открытия кейсов')),
                ('registration_open', models.BooleanField(default=True, verbose_name='Регистрация открыта')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
        migrations.CreateModel(
            name='CheckPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='core.event', verbose_name='Мероприятие')),
            ],
            options={
                'verbose_name': 'Контрольная точка',
                'verbose_name_plural': 'Контрольные точки',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='core.event', verbose_name='Мероприятие')),
            ],
            options={
                'verbose_name': 'Кейс',
                'verbose_name_plural': 'Кейсы',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название команды')),
                ('is_active', models.BooleanField(default=True, verbose_name='В игре')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('captain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captained_teams', to=settings.AUTH_USER_MODEL, verbose_name='Капитан')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='core.event', verbose_name='Мероприятие')),
                ('members', models.ManyToManyField(blank=True, related_name='teams', to=settings.AUTH_USER_MODEL, verbose_name='Участники')),
                ('selected_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.case', verbose_name='Выбранный кейс')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команды',
                'unique_together': {('name', 'event')},
            },
        ),
        migrations.CreateModel(
            name='TeamCheckPointStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_passed', models.BooleanField(default=False, verbose_name='Пройдена')),
                ('passed_at', models.DateTimeField(blank=True, null=True, verbose_name='Время прохождения')),
                ('checkpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.checkpoint', verbose_name='Контрольная точка')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoint_statuses', to='core.team', verbose_name='Команда')),
            ],
            options={
                'verbose_name': 'Статус прохождения КП',
                'verbose_name_plural': 'Статусы прохождения КП',
                'unique_together': {('team', 'checkpoint')},
            },
        ),
    ]
