# Generated by Django 6.0.5 on 2026-05-10 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='captain_name',
            field=models.CharField(default='', max_length=200, verbose_name='ФИО капитана'),
        ),
    ]
